apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search
    containerapp.apps.tanzu.vmware.com/class: kubernetes
  name: search
spec:
  content:
    buildTimestamp: "2024-08-15T23:35:37Z"
    packageImage: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:353e666257148e6a715ac1b37a6f5878e476f5a6c8bb051ddbebdf149ae16bd0
    packageRefName: search.apps.local
    packageVersion: 20240815.2335.37025
    summary: image:d0b27f7 @ 2024-08-15T23:35:37Z
    version: 20240815.2335.37025
  health:
    maxUnavailableReplicas: 10%
  image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:d0b27f77e84a89fbafbccf4bd6f3b624a7e207ab590de2afc0e756e5d8a1d39d
  nonSecretEnv:
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.health.probes.enabled=true
      -Dserver.port=8080
  ports:
  - name: main
    port: 8080
  probes:
    liveness:
      httpGet:
        path: /livez
        port: 8080
        scheme: HTTP
    readiness:
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
    startup:
      failureThreshold: 120
      httpGet:
        path: /readyz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 1
  relatedRefs:
  - for: kubernetes.list-replicas
    kind: Pod
    labelSelector: containerapp.apps.tanzu.vmware.com/app-name=search
  - apiGroup: apps
    for: kubernetes.service-binding-target
    kind: Deployment
    name: search
  - for: kubernetes.service-target
    kind: Service
    name: search
  - for: kubernetes.scale-replicas
    keyPath: .data['values.yml']->[yaml].replicas
    kind: Secret
    name: search-values
  - for: kubernetes.scale-resources
    keyPath: .data['values.yml']->[yaml].resources
    kind: Secret
    name: search-values
  - for: kubernetes.set-secret-env
    keyPath: .data['values.yml']->[yaml].secretEnv
    kind: Secret
    name: search-values
  - apiGroup: packaging.carvel.dev
    for: kubernetes.delete
    kind: PackageInstall
    name: search
  - apiGroup: data.packaging.carvel.dev
    for: kubernetes.delete
    kind: Package
    name: search.apps.local.20240815.2335.37025
  - for: kubernetes.delete
    kind: Secret
    name: search-values
  - for: kubernetes.set-content-hash
    keyPath: .data['values.yml']->[yaml].contentHash
    kind: Secret
    name: search-values
  - for: kubernetes.set-content-version
    keyPath: .data['values.yml']->[yaml].contentVersion
    kind: Secret
    name: search-values
  resources:
    cpu: 300m
    memory: 1Gi
