apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/search
  creationTimestamp: null
  name: search.apps.local.20240819.2233.42764
spec:
  refName: search.apps.local
  releasedAt: "2024-08-19T22:38:26Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:287d8c3b3bdbfe4d545c6a2ba5398aeb864ed5793160c6a56bb8f11012f0610d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240819.2233.42764
