apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/single-image-single-app
  creationTimestamp: null
  name: single-image-single-app.apps.local.20240821.2134.49954
spec:
  refName: single-image-single-app.apps.local
  releasedAt: "2024-08-21T21:36:10Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-central1-docker.pkg.dev/app-last-mile/ucp/ca-registry@sha256:78f2fce691308e69ce67989d8747aa60788e483d2e68316f2710e90d9c44e3b9
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240821.2134.49954
